# Generated by Django 5.0.3 on 2024-03-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("zomato", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("name", models.CharField(max_length=200)),
                ("online_order", models.BooleanField(default=False)),
                ("book_table", models.BooleanField(default=False)),
                ("rate", models.FloatField()),
                ("votes", models.IntegerField()),
                ("location", models.CharField(max_length=200)),
                ("rest_type", models.CharField(max_length=200)),
                ("cuisines", models.CharField(max_length=200)),
                ("cost2plates", models.FloatField()),
                ("listed_in_type", models.CharField(max_length=200)),
                ("area", models.CharField(max_length=200)),
                ("ratings", models.CharField(max_length=600)),
                ("reviews", models.CharField(max_length=1000)),
                ("count", models.IntegerField()),
                ("sentiments", models.CharField(max_length=200)),
                ("summaries", models.CharField(max_length=200)),
                ("sentiment_label", models.CharField(max_length=200)),
                ("index_f", models.IntegerField()),
            ],
        ),
    ]
