# Generated by Django 5.0.3 on 2024-03-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "zomato",
            "0004_alter_restaurant_reviews_alter_restaurant_sentiments_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="ratings",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="reviews",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="sentiments",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="url",
            field=models.URLField(max_length=10000),
        ),
    ]
