# Generated by Django 5.0.3 on 2024-03-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zomato", "0006_alter_restaurant_summaries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="reviews",
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="sentiments",
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="summaries",
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="url",
            field=models.URLField(max_length=20000),
        ),
    ]
