# Generated by Django 5.0.3 on 2024-03-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "zomato",
            "0007_alter_restaurant_reviews_alter_restaurant_sentiments_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="ratings",
            field=models.CharField(max_length=5000),
        ),
    ]
