# Generated by Django 5.0.3 on 2024-03-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zomato", "0008_alter_restaurant_ratings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="area",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="cuisines",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="listed_in_type",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="location",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="name",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="rest_type",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="reviews",
            field=models.CharField(max_length=50000),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="sentiment_label",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="sentiments",
            field=models.CharField(max_length=50000),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="summaries",
            field=models.CharField(max_length=50000),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="url",
            field=models.URLField(max_length=50000),
        ),
    ]
